### ISSUE TITLE
Version mismatch in Maven repository

### ISSUE THREAD

**Issue by rreckel** [RMSone/slick-cats#34]
Hi,

It seems that an old version 0.7-RC1 is published in the Maven repository.
Would it be possible to upload the right (latest) version of slick-cats to Maven central

Thanks a lot.
Roll

**Comment by 23will** [comment]
Sorry, about that. There is some confusion between Sonatype and Maven as that is an old version that was deleted a long time ago on Sonatype. Will push a `0.7.1-RC1` to avoid any further confusion

**Comment by 23will** [comment]
`0.7.1-RC1` has been published/synced to Maven central

**Comment by rreckel** [comment]
Wow, that was quick.
Thanks a lot, it works like a charm now.
Thank you for the great work!
