### ISSUE TITLE
Instance for `Semigroupal[DBIO]`

### ISSUE THREAD

**Issue by AesaKamar** [RMSone/slick-cats#41]
This would allow for us to combine multiple DBIOs in an applicative way. 

`dbioA |@| dbioB |@| dbioC` should have the type of `DBIO[(A, B, C)]` 

A simple implementation of the requisite function: 

```
product[A, B]( fa: DBIO[A], fb: DBIO[B]): DBIO[(A, B)] = 
   (fa zip fb)
```

I think it was renamed from Cartesian to Semigroupal btw.

**Comment by Tvaroh** [comment]
Hi, @AesaKamar.

`Semigroupal` is a supertype of `Applicative` which is a supertype of `Monad` for which we already provide an instance. So I believe applicative syntax it should work already. Is that what you want?

**Comment by AesaKamar** [comment]
Hmm, maybe I'm importing something incorrectly. 

Thanks for the info tho~
