### ISSUE TITLE
Project depends on scalacheck outside of "Test"

### ISSUE THREAD

**Issue by Daenyth** [RMSone/slick-cats#42]
`"org.typelevel" %% "cats-laws" % "1.0.1",` is declared without `% "Test"`, and it depends on `cats-kernel-laws` which depends on `scalacheck`.

This is causing my builds to somewhat non-deterministic in which scalacheck version makes it onto my classpath, so I need to work around it with `exclude`.

Assuming nothing from `cats-laws` is used in non-test code paths, fixing this should only take adding `% "Test"`

**Comment by Tvaroh** [comment]
Thanks for the report, are you going to create a PR?

**Comment by Daenyth** [comment]
Sure

**Comment by Daenyth** [comment]
btw the workaround right now is
```
    ("com.rms.miu" %% "slick-cats" % Version.slickCats)
      .excludeAll(
        // https://github.com/RMSone/slick-cats/issues/42
        "org.scalacheck" %% "scalacheck",
        "org.typelevel" %% "cats-laws",
        "org.typelevel" %% "cats-kernel-laws"
      ),
```
