### ISSUE TITLE
Compatibility with DBIOAction to preserve effect type?

### ISSUE THREAD

**Issue by alexklibisz** [RMSone/slick-cats#56]
Hi, neat project!

I'm wondering if you have any ideas about making the instances compatible with a DBIOAction instead of a DBIO?

I'm trying to use the library in a project where we make use of the effect type (the `E` in `DBIOAction[R, S, E]`) in order to permit/deny actions via specific database handles. [Similar to this example](https://danielwestheide.com/blog/put-your-writes-where-your-master-is-compile-time-restriction-of-slick-effect-types/).

Using `DBIO[A]` means we lose track of the effect type when using monad transformers. For example, if I pass a `DBIOAction[Option[Int], NoStream, Effect.Read]` into an `OptionT` then it comes out as a `DBIOAction[Option[Int], NoStream, Effect.All]`. 

Curious if you have any thoughts on how one might preserve the effect type? I have a feeling it might not be possible, since `F[_]` only has one slot for a type parameter.

**Comment by Tvaroh** [comment]
HI @alexklibisz - it's not possible with the current implementation. But may be potentially possible if written with the `DBIOAction` in mind. But yeah - that's not provided. 🤷‍♂️

**Comment by alexklibisz** [comment]
Yeah it's a tricky exercise. It seems you 'd have to:
1) Have aliases for DBIOActions with an effect but only one type "slot" to satisfy the F[_] required by Cats' typeclasses. This is not so hard, but then you need to..
2) Have some way to combine the `Effect` types in the "background" as you apply transformations on the monad transformer.

Some more discussion here: https://www.reddit.com/r/scala/comments/lr09iz/is_it_possible_to_use_cats_monad_transformers/

I'll close for now and keep passively thinking on it to see if I might find a way to do this.
